apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakshitkashyap/product-service:v1
spec:
  replicas: 2 # Runs two copies for high availability
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: rakshitkashyap/product-service:v1 # The image you pushed!
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/productservice"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"